### ISSUE TITLE
README 中 CF API 的替换规则出错

### ISSUE THREAD

**Issue by youzi-2333** [mcmod-info-mirror/mcim#77]
- 原始 URL：`https://api.curseforge.com/v1/mods/search?gameId=432&sortField=2&sortOrder=desc&pageSize=40&classId=6&categoryId=0`
- 错误镜像 URL：`https://mod.mcimirror.top/v1/curseforge/mods/search?gameId=432&sortField=2&sortOrder=desc&pageSize=40&classId=6&categoryId=0`
- 正确 URL：`https://mod.mcimirror.top/curseforge/mods/search?gameId=432&sortField=2&sortOrder=desc&pageSize=40&classId=6&categoryId=0`
- 正确替换规则：`api.curseforge.com/v1` -> `mod.mcimirror.top/curseforge`

**Comment by z0z0r4** [comment]
嗯？sorry，我忘了还有个 `v1`

**Comment by z0z0r4** [comment]
已修改部分接口路径 https://mod.mcimirror.top/docs
