### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'warn'

### ISSUE THREAD

**Issue by pysio2007** [mcmod-info-mirror/mcim#85]
在文件 app/utils/middleware/timing.py 中
warn 已经被弃用了 应该使用 warning
https://github.com/mcmod-info-mirror/mcim/blob/a14986a7426c24c3a3c997956485077ecf1f909f/app/utils/middleware/timing.py#L18-L23

**Comment by z0z0r4** [comment]
那我知道为啥日志会有问题了...这个是在GitHub web 直接写的
