### ISSUE TITLE
header ETag

### ISSUE THREAD

**Issue by z0z0r4** [mcmod-info-mirror/mcim#93]

**Comment by z0z0r4** [comment]
StreamingResponse

**Comment by z0z0r4** [comment]
![{8608A8FD-76F0-4B14-93F9-9C31B7EB445F}](https://github.com/user-attachments/assets/be2ae853-8501-4702-b62d-d8500bb8e2f8)

**Comment by zyxkad** [comment]
热知识，etag的值需要使用双引号""包起来
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/ETag

**Comment by z0z0r4** [comment]
> 热知识，etag的值需要使用双引号""包起来 [developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/ETag](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/ETag)

crazy，我当时看 MDN 以为是字符串（

**Comment by zyxkad** [comment]
用双引号包起来的原因是可以有多个用逗号分隔的 ETag，比如:
```
ETag: "md5:aaa", "sha256:bbb", "sha512:ccc"
```

**Comment by z0z0r4** [comment]
草，etag 还能多个的啊
