### ISSUE TITLE
动态接口有误

### ISSUE THREAD

**Issue by z0z0r4** [mcmod-info-mirror/mcim#96]
https://github.com/Hex-Dragon/PCL2/issues/4811

**Comment by z0z0r4** [comment]
完全没看懂哪里有问题，我差不多该自闭了

https://github.com/mcmod-info-mirror/mcim/blob/322c5f4f8663676e7da733355efde10bd95a3271/app/controller/modrinth/v2/__init__.py#L406

**Comment by zyxkad** [comment]
POST请求的缓存不会检查request body，所以需要使用URL param或者完全不缓存该API

**Comment by zyxkad** [comment]
https://github.com/mcmod-info-mirror/mcim/blob/main/app/utils/response/__init__.py#L36

可以在此处检查一下是否为post请求

**Comment by z0z0r4** [comment]
> POST请求的缓存不会检查request body，所以需要使用URL param或者完全不缓存该API

原来如此...

**Comment by z0z0r4** [comment]
正在抽测接口完整性…

**Comment by z0z0r4** [comment]
已经给 POST 加上 `no-cache` 了，当前 CDN 测试无碍，重新开启缓存
