### ISSUE TITLE
收集 `Trustable` 比率

### ISSUE THREAD

**Issue by z0z0r4** [mcmod-info-mirror/mcim#98]
到底少了多少信息...

**Comment by zyxkad** [comment]
这个Trustable是什么东西?

**Comment by z0z0r4** [comment]
> 这个Trustable是什么东西?

https://github.com/mcmod-info-mirror/mcim#%E7%BC%93%E5%AD%98%E6%80%9D%E8%B7%AF

基本思路为 忽视数据是否过期，以及 忽略数据是否不全，无条件返回已有数据，在过期、未找到等情况下先返回数据，然后后台拉取源站。

不可信的响应将在 headers 内提供 Trustable 参数

**Comment by z0z0r4** [comment]
`Gauge` 好像也不是比例...就这样吧
